<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'title' => 'Cien Años de Soledad',
                'author' => 'Gabriel García Márquez',
                'category' => 'Novelas',
                'price' => 24.50,
                'original_price' => 28.00,
                'cover_image' => '/src/assets/images/book_cien_anos_soledad_1790638655794.jpg',
                'cover_theme' => 'emerald',
                'description' => 'La cumbre del realismo mágico hispanoamericano. Narra la fascinante historia de las siete generaciones de la familia Buendía en el mítico pueblo de Macondo, desde su fundación hasta su misteriosa desaparición en un torbellino de memoria y profecías.',
                'total_copies' => 18,
                'available_copies' => 18,
                'rating' => 4.9,
                'reviews_count' => 384,
                'pages' => 471,
                'publisher' => 'Editorial Sudamericana',
                'publication_year' => 1967,
                'isbn' => '978-0307474728',
                'is_featured' => true,
                'is_bestseller' => true,
            ],
            [
                'title' => 'Cosmos',
                'author' => 'Carl Sagan',
                'category' => 'Ciencia',
                'price' => 29.90,
                'original_price' => 34.00,
                'cover_image' => '/src/assets/images/book_cosmos_astronomia_1790638666212.jpg',
                'cover_theme' => 'navy',
                'description' => 'Una monumental travesía a través de quince mil millones de años de evolución cósmica que han transformado la materia en vida y conciencia. Carl Sagan combina ciencia rigurosa con poesía para explorar nuestro lugar en el vasto océano estelar.',
                'total_copies' => 12,
                'available_copies' => 12,
                'rating' => 4.9,
                'reviews_count' => 295,
                'pages' => 384,
                'publisher' => 'Planeta Divulgación',
                'publication_year' => 1980,
                'isbn' => '978-8408169734',
                'is_featured' => true,
                'is_bestseller' => true,
            ],
            [
                'title' => 'Meditaciones',
                'author' => 'Marco Aurelio',
                'category' => 'Filosofía',
                'price' => 19.00,
                'original_price' => null,
                'cover_image' => '/src/assets/images/book_filosofia_clasica_1790638673844.jpg',
                'cover_theme' => 'terracotta',
                'description' => 'El diario íntimo y espiritual del emperador filósofo de Roma. Escrito durante campañas militares en la frontera del Danubio, ofrece una guía inmortal de templanza, resiliencia estoica, deber cívico y serenidad ante las vicisitudes del destino.',
                'total_copies' => 25,
                'available_copies' => 25,
                'rating' => 4.8,
                'reviews_count' => 420,
                'pages' => 224,
                'publisher' => 'Gredos Clásicos',
                'publication_year' => 180,
                'isbn' => '978-8424938239',
                'is_featured' => true,
                'is_bestseller' => true,
            ],
            [
                'title' => 'El Hombre que Calculaba',
                'author' => 'Malba Tahan',
                'category' => 'Matemáticas',
                'price' => 18.50,
                'original_price' => 22.00,
                'cover_image' => '',
                'cover_theme' => 'amber',
                'description' => 'En los exóticos caminos de Bagdad, Beremiz Samir resuelve con asombrosa agudeza matemática los problemas y disputas más ingeniosos de mercaderes, jeques y sabios. Una aventura literaria que hace amar las matemáticas.',
                'total_copies' => 14,
                'available_copies' => 14,
                'rating' => 4.7,
                'reviews_count' => 168,
                'pages' => 288,
                'publisher' => 'Vergara Ediciones',
                'publication_year' => 1938,
                'isbn' => '978-9501524345',
                'is_featured' => false,
                'is_bestseller' => true,
            ],
            [
                'title' => 'Sapiens: De animales a dioses',
                'author' => 'Yuval Noah Harari',
                'category' => 'Historia',
                'price' => 26.00,
                'original_price' => 30.00,
                'cover_image' => '',
                'cover_theme' => 'terracotta',
                'description' => 'Una audaz mirada panorámica a cómo una especie de simio insignificante llegó a dominar el planeta Tierra mediante la revolución cognitiva, la invención de mitos compartidos y el avance implacable de la ciencia.',
                'total_copies' => 20,
                'available_copies' => 20,
                'rating' => 4.8,
                'reviews_count' => 512,
                'pages' => 496,
                'publisher' => 'Debate Editorial',
                'publication_year' => 2014,
                'isbn' => '978-8499926223',
                'is_featured' => true,
                'is_bestseller' => true,
            ],
            [
                'title' => 'Ficciones',
                'author' => 'Jorge Luis Borges',
                'category' => 'Novelas',
                'price' => 21.00,
                'original_price' => null,
                'cover_image' => '',
                'cover_theme' => 'navy',
                'description' => 'Laberintos infinitos, bibliotecas cósmicas, enciclopedias apócrifas y espejos que multiplican el misterio del universo en cuentos que revolucionaron la literatura contemporánea universal.',
                'total_copies' => 16,
                'available_copies' => 16,
                'rating' => 4.9,
                'reviews_count' => 310,
                'pages' => 224,
                'publisher' => 'Alianza Editorial',
                'publication_year' => 1944,
                'isbn' => '978-8420658773',
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'title' => 'Veinte Poemas de Amor y una Canción Desesperada',
                'author' => 'Pablo Neruda',
                'category' => 'Poesía',
                'price' => 15.00,
                'original_price' => 18.00,
                'cover_image' => '',
                'cover_theme' => 'crimson',
                'description' => 'El poemario de amor en español más leído y celebrado de todos los tiempos. Juventud apasionada, melancolía marina y la emoción pura de las despedidas en versos inolvidables.',
                'total_copies' => 30,
                'available_copies' => 30,
                'rating' => 4.8,
                'reviews_count' => 275,
                'pages' => 112,
                'publisher' => 'Losada',
                'publication_year' => 1924,
                'isbn' => '978-8420672724',
                'is_featured' => false,
                'is_bestseller' => true,
            ],
            [
                'title' => 'Breve Historia del Tiempo',
                'author' => 'Stephen Hawking',
                'category' => 'Ciencia',
                'price' => 22.50,
                'original_price' => 26.00,
                'cover_image' => '',
                'cover_theme' => 'slate',
                'description' => 'Desde el Big Bang hasta los agujeros negros, Stephen Hawking explica los misterios más profundos del universo físico en un lenguaje cautivador y accesible para cualquier lector curioso.',
                'total_copies' => 10,
                'available_copies' => 10,
                'rating' => 4.7,
                'reviews_count' => 340,
                'pages' => 256,
                'publisher' => 'Crítica Libros',
                'publication_year' => 1988,
                'isbn' => '978-8498922486',
                'is_featured' => false,
                'is_bestseller' => false,
            ],
        ];

        foreach ($books as $b) {
            $cat = Category::where('name', $b['category'])->first();
            $b['category_id'] = $cat?->id;
            Book::firstOrCreate(['isbn' => $b['isbn']], $b);
        }
    }
}
